# Generated by Django 3.2.4 on 2021-07-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_topstorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_new',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
