# Generated by Django 3.2.6 on 2021-09-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_latest_new_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Latest_new',
        ),
        migrations.DeleteModel(
            name='topstorie',
        ),
    ]
