# Generated by Django 3.2.6 on 2021-09-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210915_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email_form',
            new_name='Email',
        ),
    ]
