# Generated by Django 3.2.6 on 2021-09-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_email_form_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_cover_photo', models.ImageField(blank=True, default='profile-photo.png', upload_to='')),
                ('profile_photo', models.ImageField(blank=True, default='profile-photo.png', upload_to='')),
                ('first_name', models.CharField(max_length=14)),
                ('last_name', models.CharField(max_length=14)),
                ('slug', models.SlugField()),
                ('about_snippet', models.CharField(max_length=60)),
                ('followers', models.IntegerField(blank=True, default=1)),
                ('events', models.IntegerField(blank=True, default=0)),
                ('donations', models.IntegerField(blank=True, default=0)),
                ('event_photos', models.ImageField(blank=True, upload_to='')),
                ('address_field', models.CharField(blank=True, max_length=40)),
                ('mobile_contact', models.PositiveBigIntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook_contact', models.CharField(blank=True, max_length=20)),
                ('twitter_contact', models.CharField(blank=True, max_length=20)),
                ('about', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
