# Generated by Django 3.2.6 on 2021-09-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
    ]
