# Generated by Django 3.2.6 on 2021-09-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_profiles_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='event_photos',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_cover_photo',
            field=models.ImageField(blank=True, default='profile-photo.png', upload_to='media/profile/profile_cover_photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile-photo.png', upload_to='media/profile/profile_photos/'),
        ),
        migrations.CreateModel(
            name='Profile_event_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_photos', models.ImageField(blank=True, upload_to='media/profile/events_images/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
        ),
    ]
