# Generated by Django 3.2.6 on 2021-09-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210918_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_event_photos',
            old_name='event_photos',
            new_name='event_photo',
        ),
    ]
