# Generated by Django 3.2.6 on 2021-09-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_event_photos_profile_event_photos_event_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_event_photos',
            new_name='Profile_event_photo',
        ),
        migrations.RenameField(
            model_name='profile_event_photo',
            old_name='event_photo',
            new_name='event_photos',
        ),
    ]
