# Generated by Django 3.2.6 on 2021-09-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210918_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_snippet',
            field=models.CharField(max_length=120),
        ),
    ]
