# Generated by Django 3.2.6 on 2021-09-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_profile_about_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_cover_photo',
            field=models.ImageField(blank=True, default='profile_cover_photos/profile-photo.png', upload_to='media/profile/profile_cover_photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/profile-photo.png', upload_to='media/profile/profile_photos/'),
        ),
    ]
