# Generated by Django 3.2.6 on 2021-09-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210918_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_cover_photo',
            field=models.ImageField(blank=True, default='profile/profile_cover_photos/profile-photo.png', upload_to='media/profile/profile_cover_photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile/profile_photos/profile-photo.png', upload_to='media/profile/profile_photos/'),
        ),
    ]
