# Generated by Django 3.2.6 on 2021-09-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210918_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(default='news-images/photos-gallery icon.png', upload_to='news-images/')),
                ('slug', models.SlugField()),
                ('story', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_cover_photo',
            field=models.ImageField(blank=True, default='profile/profile_cover_photos/profile-photo.png', upload_to='profile/profile_cover_photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile/profile_photos/profile-photo.png', upload_to='profile/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='profile_event_photo',
            name='event_photos',
            field=models.ImageField(blank=True, default='profile/events_images/photos-gallery icon.png', upload_to='profile/events_images/'),
        ),
    ]
