# Generated by Django 3.2.6 on 2021-09-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210921_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='story_snippet',
            field=models.CharField(default='meet Harvey', max_length=200),
        ),
    ]
