# Generated by Django 3.2.6 on 2021-09-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_advert_advert_image_images_topstory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='advert_image',
            new_name='Advert_images',
        ),
        migrations.RenameModel(
            old_name='images',
            new_name='Topstory_images',
        ),
    ]
