# Generated by Django 3.2.6 on 2021-09-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210925_1859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advert_images',
            new_name='Advert_image',
        ),
    ]
