# Generated by Django 3.2.6 on 2021-10-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_followers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers_email',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='followers_email',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
